services:
  app:
    build: .
    volumes:
      - .:/app
      - vendor-data:/app/vendor
    working_dir: /app
    entrypoint: ["php", "index.php"]
    stdin_open: true
    tty: true

  test:
    build: .
    volumes:
      - .:/app
      - vendor-data:/app/vendor
    working_dir: /app
    entrypoint: ["vendor/bin/phpunit"]
    command: ["tests"]

  phpcs:
    image: jakzal/phpqa
    volumes:
      - .:/app
    working_dir: /app
    command: phpcs --standard=PSR12 src

  phpcbf:
    image: jakzal/phpqa
    volumes:
      - .:/app
    working_dir: /app
    command: phpcbf --standard=PSR12 src 

volumes:
  vendor-data: