version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - vendor-data:/app/vendor
    working_dir: /app
    entrypoint: ["php", "index.php"]
    stdin_open: true
    tty: true

  test:
    build: .
    volumes:
      - .:/app
      - vendor-data:/app/vendor
    working_dir: /app
    entrypoint: ["vendor/bin/phpunit"]
    command: ["tests"]

volumes:
  vendor-data: