services:
  app:
    build: .
    container_name: wawibox-app
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["php", "index.php"]
    stdin_open: true
    tty: true

  test:
    build: .
    container_name: wawibox-test
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["vendor/bin/phpunit"]
    command: ["tests"]